# ------------------------------- trim
trim_filepath     : "./data/33_4_DR/gx040021.mp4"
trim_outpath      : "./data/videoset/vid_3.mp4"
trim_start        : "200" # can be in clock format or seconds format
trim_end          : "300" # same as above



# ------------------------------- fragment
frag_filepath     : "./data/gx050023.mp4"
frag_fps          : 3
frag_start_time   : "00:02:00"
frag_end_time     : "00:02:05"



# ------------------------------- scanf
species               : "oniger"
scanf_model_path      : "./model/oniger.pt"
scanf_conf_thres      : 0.25
scanf_iou_thres       : 0.7
scanf_rescale_size    : 640
scanf_video_path      : "./data/videoset/vid_3.mp4"
scanf_store_images    : true
scanf_full_scan       : false
scanf_start_time      : "00:00:42"
scanf_end_time        : "00:00:46"
scanf_interval        : 30
scanf_fps             : 60



# ------------------------------- scanf-bulk
species               : "oniger"
bulk_model_path       : "./model/oniger.pt"
bulk_video_dir        : "./data/videoset"
bulk_conf_thres       : 0.25
bulk_iou_thres        : 0.7
bulk_rescale_size     : 640
bulk_interval         : 30
bulk_fps              : 60

# ------------------------------- measure
left_cam_json         : "./data/stereo-unity/left-cap.json"
right_cam_json        : "./data/stereo-unity/right-cap.json"
output_file           : "./report/measure-result.csv"
cam_separation        : 1.0     #meter
cam_hfov              : 86
cam_vfov              : 55.343
cam_hdev              : 7
lon_coef_a            : 57.3287
lon_coef_t            : 0.000969889  
lat_coef_a            : 57.676   
lat_coef_t            : 0.000963112 